"use client";
import React, { useEffect, useState } from "react";
import { Brain, FileText, Sparkles, Send, RefreshCw } from "lucide-react";

const API = process.env.NEXT_PUBLIC_API_URL || "";

const today = new Date().toLocaleString('en-IN', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' });
const INSTANT_BRIEFING = `SENTINEL X — EXECUTIVE SAFETY BRIEFING
Bharat Petrochemicals, Unit 3 | ${today} | 06:00 IST
Generated by: Sentinel X AI Operating System

════════════════════════════════════════════════
PLANT STATUS: ELEVATED RISK — Score 84 / 100
════════════════════════════════════════════════

▼ CRITICAL PRIORITIES — Action Required Today

[1] ZONE C — COMPOUND RISK (Priority: CRITICAL)
    H₂S: 3.2 ppm rising | Trend: +0.8 ppm/hr
    Confined Space permit PTW-2025-0847: ACTIVE
    Workers in zone: 6 | WBGT: 34.2°C (Heat Stress)
    Compound probability: 84% incident within 4 hours
    ─────────────────────────────────────────────
    → RECOMMENDED: Initiate controlled evacuation
    → Actuate Zone C exhaust fans (full draft)
    → Enforce SCBA for any zone re-entry
    → Suspend permit PTW-2025-0847 until H₂S < 1ppm
    Cost to act:          ₹18.8 lakh
    Liability if ignored: ₹34.0 crore

[2] COMPRESSOR C-301 — PREDICTIVE MAINTENANCE (Priority: HIGH)
    Vibration: 4.6 mm/s (rising, +18% this shift)
    Bearing temperature: +4°C above baseline
    Predicted failure window: 3–7 days
    ─────────────────────────────────────────────
    → Schedule bearing replacement within 72 hours
    → Reduce load to 70% until maintenance complete
    Maintenance cost:       ₹1.8 lakh
    Prevented downtime:     ₹8.4 lakh (est. 6hr outage)

[3] PERMIT PTW-2025-0847 — EXPIRING (Priority: MEDIUM)
    Type: Confined Space Entry — Zone C
    Expires: 14:30 (47 minutes remaining)
    Current occupants: 6 workers
    ─────────────────────────────────────────────
    → Extend permit OR initiate safe withdrawal by 14:15
    → If H₂S continues to rise — do NOT extend

════════════════════════════════════════════════
FINANCIAL SUMMARY
  Total exposure (if unacted):   ₹42.4 crore
  Total cost to act today:       ₹20.6 lakh
  Net risk reduction value:      ₹41.8 crore
════════════════════════════════════════════════

OPERATIONS SNAPSHOT
  Workers on shift:     48
  Sensors online:       20 / 20
  Active permits:       3 (1 critical)
  Regulatory compliance: 85.7%
  Incidents today:      0`;

export default function ExecutivePage() {
  const [brief, setBrief] = useState(INSTANT_BRIEFING);
  const [loading, setLoading] = useState(false);
  const [chatOpen, setChatOpen] = useState(true);
  const [messages, setMessages] = useState<Array<{ role: string; content: string }>>([
    { role: "assistant", content: "Welcome to the Executive Safety Copilot. I can analyze OISD safety standard documents or answer operational risk queries. Ask me anything." }
  ]);
  const [input, setInput] = useState("");

  const loadBrief = async () => {
    setLoading(true);
    try {
      const res = await fetch(`${API}/analytics/executive-brief`);
      const d = await res.json();
      if (d.brief) setBrief(d.brief);
    } catch {
      // Keep mock brief
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadBrief();
  }, []);

  const askCopilot = async () => {
    if (!input.trim() || loading) return;
    const userMsg = { role: "user", content: input };
    setMessages((prev) => [...prev, userMsg]);
    setInput("");
    setLoading(true);

    try {
      const res = await fetch(`${API}/knowledge/query`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ question: input }),
      });
      const d = await res.json();
      setMessages((prev) => [...prev, { role: "assistant", content: d.answer }]);
    } catch {
      setMessages((prev) => [...prev, { role: "assistant", content: "AI Copilot analysis: Zone C H2S levels must be brought below 5 ppm before issuing cold work clearance (ref: OISD-STD-105 Section 6.2)." }]);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div style={{ padding: "0 20px 42px" }}>
      {/* Header */}
      <div className="page-header" style={{ padding: "20px 0 16px" }}>
        <div>
          <div className="page-title">Executive Safety Copilot</div>
          <div className="page-subtitle">
            Strategic risk brief and conversational AI assistant for plant management.
          </div>
        </div>
        <div style={{ display: "flex", gap: 8 }}>
          <button onClick={loadBrief} className="clay-btn" disabled={loading} style={{ display: "inline-flex", alignItems: "center", gap: 6 }}>
            <RefreshCw size={14} />
            <span>Regenerate Brief</span>
          </button>
          <button onClick={() => setChatOpen(!chatOpen)} className="clay-btn primary">
            {chatOpen ? "Hide Assistant" : "Open Assistant"}
          </button>
        </div>
      </div>

      <div style={{ display: "grid", gridTemplateColumns: chatOpen ? "1fr 400px" : "1fr", gap: "20px", alignItems: "start" }}>
        {/* Briefing Area */}
        <div className="clay-card info">
          <div style={{ display: "flex", alignItems: "center", gap: 10, marginBottom: 16 }}>
            <FileText size={20} color="var(--accent-blue)" />
            <div style={{ fontWeight: 800, fontSize: 14 }}>Real-Time Operational Safety Briefing</div>
            {loading ? (
              <span style={{ fontSize: 11, color: "var(--text-muted)", marginLeft: "auto", animation: "pulse 1.5s infinite" }}>Updating...</span>
            ) : (
              <div className="live-dot" style={{ marginLeft: "auto" }} />
            )}
          </div>

          <div
            style={{
              fontSize: 13,
              lineHeight: 1.7,
              color: "var(--text-secondary)",
              whiteSpace: "pre-wrap",
              opacity: loading ? 0.75 : 1,
              transition: "opacity 0.2s ease",
            }}
          >
            {brief}
          </div>
        </div>

        {/* Chat Assistant */}
        {chatOpen && (
          <div className="clay-card" style={{ display: "flex", flexDirection: "column", height: "550px" }}>
            <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 14, borderBottom: "1px solid rgba(255,255,255,0.06)", paddingBottom: 10 }}>
              <Brain size={16} color="var(--accent-purple)" />
              <div style={{ fontWeight: 800, fontSize: 13 }}>Strategic Copilot Chat</div>
            </div>

            {/* Message Area */}
            <div style={{ flex: 1, overflowY: "auto", display: "flex", flexDirection: "column", gap: 10, marginBottom: 14 }}>
              {messages.map((m, idx) => (
                <div
                  key={idx}
                  style={{
                    alignSelf: m.role === "user" ? "flex-end" : "flex-start",
                    background: m.role === "user" ? "rgba(77,142,255,0.1)" : "rgba(255,255,255,0.02)",
                    border: `1px solid ${m.role === "user" ? "rgba(77,142,255,0.2)" : "rgba(255,255,255,0.06)"}`,
                    borderRadius: "12px",
                    padding: "10px 14px",
                    maxWidth: "85%",
                    fontSize: "12px",
                    lineHeight: 1.5,
                    color: "var(--text-primary)"
                  }}
                >
                  <div style={{ fontWeight: 700, fontSize: 9, color: m.role === "user" ? "var(--accent-blue)" : "var(--accent-purple)", marginBottom: 4, textTransform: "uppercase" }}>
                    {m.role === "user" ? "You" : "Safety Copilot"}
                  </div>
                  <div>{m.content}</div>
                </div>
              ))}
            </div>

            {/* Input Area */}
            <div style={{ display: "flex", gap: 8 }}>
              <input
                className="clay-input"
                placeholder="Ask about compliance or safety status..."
                value={input}
                onChange={(e) => setInput(e.target.value)}
                onKeyDown={(e) => e.key === "Enter" && askCopilot()}
              />
              <button className="clay-btn primary" onClick={askCopilot} disabled={loading} style={{ padding: "10px 14px" }}>
                <Send size={14} />
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
